apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-directories-generator-ex2
  namespace: argocd
spec:
  generators:
    - git:
        directories:
          - path: v09-argocd-applicationSet-1/git-generator/resources/*
          - path: v09-argocd-applicationSet-1/git-generator/resources/nginx-manifests
        repoURL: https://github.com/nuruzzaman24x/argocd-zeroto-hero.git
        revision: main
  template:
    metadata:
      name: '{{path.basename}}-application'
    spec:
      destination:
        namespace: '{{path.basename}}-ns'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/nuruzzaman24x/argocd-zeroto-hero.git
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
