apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-generator-ex2
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster       #এটি নির্দেশ করে যে এটি একটি ক্লাস্টার সিক্রেট
            #environment: staging   ##শুধুমাত্র "staging" নামে লেবেল করা ক্লাস্টারগুলোর জন্য অ্যাপ তৈরি হবে

  template:
    metadata:
      name: "{{name}}-application"

    spec:
      destination:
        namespace: cluster-generator
        server: "{{server}}"

      project: default

      source:
        path: v03-argocd-applications/helm/nginx
        repoURL: https://github.com/nuruzzaman24x/argocd-zeroto-hero.git
        targetRevision: main

      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
