apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet   #এটি ArgoCD-এর জন্য একটি ApplicationSet CRD (Custom Resource Definition) নির্দেশ করে#
metadata:
  name: cluster-generator-ex1
  namespace: argocd
spec:
  generators:      #এটি একটি Cluster Generator ব্যবহার করে সব ক্লাস্টারের জন্য স্বয়ংক্রিয়ভাবে অ্যাপ তৈরি করবে।
  - clusters: {}   #এটি ArgoCD-এর সাথে সংযুক্ত সব ক্লাস্টারের জন্য এই ApplicationSet প্রয়োগ করবে
  template:
    metadata:
      name: '{{name}}-application'   #argocd cluster list kore je output pabo tar sathe -application add hobe#
    spec:
      destination:
        namespace: cluster-generator  	#অ্যাপ কোন namespace-এ ডিপ্লয় হবে।
        server: '{{server}}'    		#এটি Cluster Generator থেকে ক্লাস্টারের API Server URL নিয়ে সেট করবে
      project: default		  		# এই অ্যাপটি default নামে একটি ArgoCD প্রজেক্টের অংশ হবে
      source:					#গিট রিপোজিটরি ও চার্ট লোকেশন
        path: v03-argocd-applications/helm/nginx
        repoURL: https://github.com/nuruzzaman24x/argocd-zeroto-hero.git
        targetRevision: main
      syncPolicy:
        automated: {}				#স্বয়ংক্রিয়ভাবে নতুন আপডেট সিঙ্ক করবে (মানুষের হস্তক্ষেপ লাগবে না)।
        syncOptions:
          - CreateNamespace=true		#যদি cluster-generator namespace না থাকে, তাহলে ArgoCD সেটি তৈরি করবে#

##Template কেন use করি?  👉 Template হলো “একটা design” বা “blueprint”  মানে:  ApplicationSet কে বলে দেয় — “প্রতিটা cluster এর জন্য app কেমন হবে”  Simple real-life example  ধরো তোমার কাছে ৩টা cluster আছে:  dev staging production  এখন তুমি চাইতেছো — সব cluster এ একই nginx app deploy হবে।  তাহলে ApplicationSet কী করে? Generator  আগে cluster খুঁজে বের করে:  dev staging production তারপর Template use করে  Template বলে:  সব cluster এর জন্য এই design follow করো
