# ################# this is template, we have to add annotations later ################
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: notify-fail
# spec:
#   template:
#     spec:
#       containers:
#         - name: mattermost-failure
#           image: nuruzzaman24x/mattermost:latest
#           command: [ "python3", "mattermost_api.py"]
#           env:
#           - name: message
#             value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync Failed ***"
#           - name: url
#             value: "172.17.0.232"
#           - name: token
#             value: "i4mcucfmridzteg7xcqgoohc6h"
#           - name: scheme
#             value: "http"
#           - name: port
#             value: "8065"
#           - name: channel_name
#             value: "argocd-course"
#           - name: team_name
#             value: "devops-bangla"
#       restartPolicy: Never
#   backoffLimit: 0

########### after add annotations ##################
apiVersion: batch/v1
kind: Job
metadata:
  name: notify-fail
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: mattermost-failure
          image: nuruzzaman24x/mattermost:latest
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync Failed ***"
          - name: url
            value: "172.17.0.232"
          - name: token
            value: "i4mcucfmridzteg7xcqgoohc6h"
          - name: scheme
            value: "http"
          - name: port
            value: "8065"
          - name: channel_name
            value: "argocd-course"
          - name: team_name
            value: "devops-bangla"
      restartPolicy: Never
  backoffLimit: 0
