# apiVersion: v1
# kind: Secret
# metadata:
#   name: external
#   labels:
#     argocd.argoproj.io/secret-type: cluster
# type: Opaque
# stringData:
#   name: external
#   server: API_SERVER_ADDRESS                         #root@newmaster01:~# cat ~/.kube/config
#   config: |
#     {
#       "bearerToken": "SERVICE_ACCOUNT_TOKEN",        #root@newmaster01:~# kubectl create token new-cluster-sa
#       "tlsClientConfig": {
#         "insecure": false,
#         "caData": "BASE64 ENCODED CERTIFICATE"     #root@newmaster01:/etc/kubernetes/pki# cat /etc/kubernetes/pki/ca.crt | base64 | tr -d "\n"
#       }
#     }


apiVersion: v1
kind: Secret
metadata:
  name: external
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: devops-bangla
  server: https://172.17.0.1:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IlNtN05NMjZXSWVFeHhNUnYwSllzalNxdjhCY1dGSE9nN2FLMGtHdmZPM28ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzc5NTQ2NTk2LCJpYXQiOjE3Nzk1NDI5OTYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im5ldy1jbHVzdGVyLXNhIiwidWlkIjoiYjIwMzlmMmYtYWM2ZS00Y2YxLWI1MjMtYjRhZjk0YjQxNWU4In19LCJuYmYiOjE3Nzk1NDI5OTYsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Om5ldy1jbHVzdGVyLXNhIn0.ZhSLcQsKL3tWQO8YioJjP8v7TfnuiZDQo_Gv4FZ0la97hXo0mfyxTvZ8tz6e1NDS92DTxsIGGBza5RcZ0VWb0nZfc_G7EgYa7ePqtlaAxcJRDVU07Swi7yqYAJzd66lVwC3j7Df-1UHyI0GjyZXZGD04EgwpqM-DEDK_OIDgg9Wp0UoBzcY8TQiaF0VvjGRGimzxPA43e7IHcEaVVwDut60vsjWB5g8QV24buONPENmTXwDqN-kL3gXv17irEu-FhiRt7sPYQDDPfjCccMQ6EihQ_GLjt0WJiv2lXDIfNb5_pw4uz_EyNTcrPAj0HHTCvhu6y2nh3L_iiOsEzWypjw",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ1NQaThrNlFKUzB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qTXhNekUwTURSYUZ3MHpOakExTWpBeE16RTVNRFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNtZ2RLejYzNHZVYUZITUkwN0FqY015cG5YM2RPUGg2Ti80RkxEb01zc3FQZ1hTU21YZE4xekJ3dUMKbStmZG9YdTJ1aW5HNXJLbUI1NTR5bTJBZmdtN014N3YxTm91Q3BtQ0treUFwWlY4anc5eGhhUG05blhYN1JDMgp4a0ZFMGtRZHFZbVZuejNMZ2E4dTFDZUJOdzVKdkdNTmVUWGZJNEtzVHZaRmNORGV6ZEk1bi9XYVRnakJra1BCClR2SUp5TDU2RnlSbjNhYmJYZ0pxajhMQWlEQzRkcW5zVktURGh4OVZWeWJkdW52WVNOZHRsRjhxYzU0VG5hb20KWmxrZ0pRRXRpR0lOc0R6T0xVd3JudUNMWWVmWlZtNWdibXo5MlV1M1poSXhNQU1kbXEvK1dEUXVHSmdCL3dMQwpxbE03UHFmRi9hWC93ekJKQnFUTHdIajlSY292QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRU1NVaERKQUkvdno5am9IaWsvd1lTZlkzVndqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0ZYeUVjOXN2NQpKUTRROWF4WHp0WXdBeUFzcyswbE1vQnhkbHk5RVhpcmJqWHVYMlA1L0xBYUtTUzFzRURTQktBS05NMC9BK2FnCmFwNnUxdFpGaXRsVmR4emNiNDhRem1rL3hFODhpeU1hd00wd2xOU25LK3QzU25WdmdrZGk2Nld5ZWsyZ2oyNFkKeEh1SUNTSTJxOXhadENrZGJUQXFDWk1OVTUzWjJIZjNVSU1TbHpyTW9PY1RWQ2pHc1ZPU1lwbnU1dkhaSStzVApKVGVBa1FQYTQ4YTNId2ZjeDNrZVkybmFFc3lTL1I0NmFmY0tpMXFzTmxYc2dYNVlmcDBuNlB5b0doZFh5d3g0Ck1wU1V0SVVQcE1idW0xVFBQQlVaV3BodTY1Q1pSdkJyYmI5dHBlSFlGUDlkeFhoc3hxZDY4NUNxVzREQWdHY20Kck9lNTh0Q1FkVTU1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
