# apiVersion: v1
# kind: Secret
# metadata:
#   name: external
#   labels:
#     argocd.argoproj.io/secret-type: cluster
# type: Opaque
# stringData:
#   name: external
#   server: API_SERVER_ADDRESS                         #root@newmaster01:~# cat ~/.kube/config
#   config: |
#     {
#       "bearerToken": "SERVICE_ACCOUNT_TOKEN",        #root@newmaster01:~# kubectl create token new-cluster-sa
#       "tlsClientConfig": {
#         "insecure": false,
#         "caData": "BASE64 ENCODED CERTIFICATE"     #root@newmaster01:/etc/kubernetes/pki# cat /etc/kubernetes/pki/ca.crt | base64 | tr -d "\n"
#       }
#     }


apiVersion: v1
kind: Secret
metadata:
  name: external
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: devops-bangla
  server: https://172.17.0.1:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik91Qkw3SVNja1cyUW9BYm0yeDhkX0hCS3QzMXpxRTMwQjRRVnhsX2RHOW8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzc5NDc2MDYzLCJpYXQiOjE3Nzk0NzI0NjMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im5ldy1jbHVzdGVyLXNhIiwidWlkIjoiNWU5MWU0ZTAtN2QwMS00ODQ5LWFkNTktOTU1NWNlMDZmYzlkIn19LCJuYmYiOjE3Nzk0NzI0NjMsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0Om5ldy1jbHVzdGVyLXNhIn0.I-yzcLs8uMUH7dOkc6R-0gypMg1OJGbzvwgeTzSz-QiG1uiMwupopJ-OHNF9KOwKAId0N8V2xGZDDJuWYY19ExlRqHKqbEJ0MfsocD56fVAWARTAsXVWkEc6v-MJ8gd02hurNc4fQTbTborCiSdnw4_y8whzs0uVgmPScYdnY4muRLBL9RYNWTuNg2VjAls2fsZUFNmRb7et54xYwwi-wu8RExjBNxwyJ9C7gliul-LeEiciBD68vdjG_k98ej1s2ziKATMJM4c-qjYD500zLIFaO7nOLMCe3mbmux4IFs0Pyc4MQKoUqtL0YZPgGj2QzHCatGotypMskdTuVrxm0w",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSGlKSUJBN3ptZGt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qRXdPVE0yTXpaYUZ3MHpOakExTVRnd09UUXhNelphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNvZjB2STNVVWxJbDBtb0lORzd0NGhZb1Y0R0dyd1REYjZXNytyazgxQlRNVWV6QzEyc1pLS3NDZ2QKZ01CNGkxTEl0OFhweEwzMnFOb3d4cGg4ZzVReC9TTnBESDA3UmtuMG1La01ZVDBWTlVlSEtNRC9ESTdwakJuMwpGaTBGNmZEcTMvcmJ0S1hLT0M0RHBCV2Q4N2tkVjhnQ3RxREsvdmI3VGsyZXN0MzlDWXhtbG1oQ1JEMVZwUy9CCmE2dzEwN0d0b2hpZGJMV21YNDBBRTExaXFNYmUzeVNkdTluK1pqdUNWNEtJTU9ZNk9ZbWRnYTdQSC9YZS83T3QKVFBQWVFVSWp6V29ETVY4S29GQWR4V3ArdVFZVEd5VFJFRDRocGVWWW5ycFZDTSt2cjVqM2ZFMEhiUVBuVTRGKwo3bDJ4Q1dGSWVENmowNyt5Rm5BSytQeDVpVi90QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTeC8ybnpib1NpYlQxTll6YldEYUJ6SzBCY1lUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkhIdkVZeXJHOQpQZTNPY2pxekJDVzNNektIK0ZERHBDNlpiTTVHNEZYMG5tRWsrVjAvdHU2dHowcDNGcXpoYzJ2Q3B4TjNLaWIzCmcwZTVFYWJWNVcrcVVMVWRwekVmU2FESER4V0Yyemk3aCtiYlpXR0xDRGJPS1EwY25ZdEJMcWlYWGo0NjNFaWIKSWc1T2F1TC9jRVVCQ3M4OWdaSXZrbmRCRVh1ZEJFUStTb1JlMmw0T2dsV1FuSnIvNE5aNFhJZnZPWm5GQnJRUApmcjI1SkJ6d20vcFIyekdkbWVkaitGYmlTZmRkblA2MnluRHNiSVAwSmZyUnlGRzRQaDV1TlY2S0xsc0FHSi8zCmw5QVVLY25TQzA0dUxVMFVoRGwwS0ltaWdKL251d0srYzRmQnJwSHd2SWsxSENOZkcyV0trZWdtT0F6KzJUSm4KNW9rSFdyUUNUR0xsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
